CREATE TABLE DECOMPOSITION (id INT NOT NULL KEY AUTO_INCREMENT, name VARCHAR(20), difficult INT );
INSERT INTO DECOMPOSITION VALUES (NULL, 'HTML', 1); 
INSERT INTO DECOMPOSITION VALUES (NULL, 'Bootstrap', 1);   
INSERT INTO DECOMPOSITION VALUES (NULL, 'GitHub', 2); 
INSERT INTO DECOMPOSITION VALUES (NULL, 'Perl', 2); 
INSERT INTO DECOMPOSITION VALUES (NULL, 'DB + MySQL', 3); 
INSERT INTO DECOMPOSITION VALUES (NULL, 'Perl Module', 3); 
 

